version: '2'

services:
  app:
    image: 'helsinki-bike-spring-boot:latest'
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/helsinkibike
      - SPRING_DATASOURCE_USERNAME=zeriab
      - SPRING_DATASOURCE_PASSWORD=zeriab
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - spring.jpa.database=POSTGRESQL
      - spring.jpa.show-sql=false
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.url=jdbc:postgresql://localhost/helsinkibike
      - spring.servlet.multipart.max-file-size=100000KB
      - spring.servlet.multipart.max-request-size=100000KB
          
  db:
    image: 'postgres:latest'
    ports:
      - "5433:5433"
    container_name: db
    environment:
      - POSTGRES_USER=zeriab
      - POSTGRES_PASSWORD=zeriab
